"use client";
import { Metadata, NextPage } from "next";
import { useState } from "react";
import { MoonLoader } from "react-spinners";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

const Home: NextPage = () => {
  const [input, setInput] = useState<string>("");
  const [error, setError] = useState(false);
  const [suggestion, setSuggestion] = useState("");
  const [loading, setLoading] = useState(false);

  const submit = async () => {
    if (input.length > 1000) return setError(true);

    setLoading(true);

    try {
      const res = await fetch("/api/marketing", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ input: input }),
      });

      const suggestion: { result: string } = await res.json();
      const { result } = suggestion;

      setSuggestion(result);
    } catch (error) {
      console.log(error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex flex-col min-h-screen">
      <header className="px-2 flex items-center justify-center w-full h-20">
        <h1 className="text-xl text-white">Marketing Copy Generator</h1>
      </header>
      <main className="h-full flex flex-col items-center justify-between p-24 space-y-6">
        <div className="relative w-full h-60">
          {error && (
            <p className="text-xs pt-1 text-red-500">
              Character limit exceeded, please enter less text
            </p>
          )}
          <textarea
            rows={3}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            className="w-full h-full border-2 border-gray-300 bg-white p-4 rounded-lg text-sm focus:outline-none resize-none"
            placeholder="Enter your topic here"
          />
          <div
            className={`absolute ${
              input.length > 1000 ? "text-red-500" : "text-gray-400"
            } bottom-2 right-2 text-xs`}
          >
            <span>{input.length}</span>/1000
          </div>
        </div>
        <button
          type="button"
          onClick={submit}
          className="bg-blue-500 h-12 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
        >
          {loading ? (
            <div className="flex justify-center items-center gap-4">
              <p>Loading...</p>
              <MoonLoader size={20} color="white" />
            </div>
          ) : (
            "Generate"
          )}
        </button>
        {suggestion && (
          <div className="mt-8">
            <h4 className="text-lg text-white font-semibold pb-2">
              Your marketing copy:
            </h4>
            <div className="relative w-full rounded-md bg-gray-100 p-4">
              <p className="text-sm text-gray-700">{suggestion}</p>
            </div>
          </div>
        )}
      </main>
    </div>
  );
};

export default Home;
